#!/bin/bash -l 
#
#PBS -N test_run
#PBS -j oe
#PBS -q s3par
#PBS -l nodes=1:ppn=16
#PBS -l walltime=24:00:00
#PBS -W group_list=moe-sc

conda activate qiskit_env

cd $PBS_O_WORKDIR
python3 run_oc.py > out_genetic_quantum10lev_test.out
