#!/bin/bash -l 
#
#PBS -N test_run
#PBS -j oe
#PBS -q s3par
#PBS -l nodes=1:ppn=16
#PBS -l walltime=24:00:00
#PBS -W group_list=moe-sc
#PBS -I 
module load psxe_2017

cd $PBS_O_WORKDIR

echo "mana"
#python3 run_solo_python.py > solo_python.out 
#python3 run_oc.py > out.out
